GET http://localhost:5000/users

###
GET http://localhost:5000/users/63ebaab543d11c98032fbd5f



###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Jacko Jj",
  "email": "Jacko@gmail.com",
  "age": 41,
  "status": "active"
}

###
PATCH http://localhost:5000/users/63eb6af925081ac7ef1a84d9
Content-Type: application/json

{
   "name": "Jacko Jj",
    "email": "Jacko@gmail.com",
    "age": 21,
    "status": "active"
}


###
Delete http://localhost:5000/users/63eb6b0625081ac7ef1a84db
Content-Type: application/json

{
   "name": "D Knight",
    "email": "knight@gmail.com",
    "gender": "Me"
}